### ISSUE TITLE
Bug: hint.label type might be a string, not a table

### ISSUE THREAD

**Issue by al-ce** [chrisgrieser/nvim-lsp-endhints#1]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.
- [X] LSP inlay hints do work correctly without this plugin when using `vim.lsp.inlay_hint.enable(true)`. (If not, then the problem lies with your LSP or your LSP configuration, not this plugin.)

### Bug Description

The `overrideHandler` function always tries to access the first value in a table for `hint.label`

https://github.com/chrisgrieser/nvim-lsp-endhints/blob/624020a8fe480266014be14037b05519f3f4a5d4/lua/lsp-endhints/override-handler.lua#L27

But here is an error I get in e.g. the `ripgrep` repo for [this impl](https://github.com/BurntSushi/ripgrep/blob/c9ebcbd8abe48c8336fb4826df7e9b6fb179de03/crates/searcher/src/line_buffer.rs#L114)

```
Error executing vim.schedule lua callback: .../nvim-lsp-endhints/lua/lsp-endhints/override-handler.lua:28: attempt to index a nil value
stack traceback:
	.../nvim-lsp-endhints/lua/lsp-endhints/override-handler.lua:28: in function 'f'
	/usr/local/share/nvim/runtime/lua/vim/iter.lua:499: in function 'fold'
	.../nvim-lsp-endhints/lua/lsp-endhints/override-handler.lua:24: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

```

Printing the `hint` table shows `label` as a string here (but rust-analyzer hints can also be tables)

```
   Info  08:40:33 AM notify.info 󰹈 :  hint: {
  label = "impl LineBufferBuilder",
  paddingLeft = true,
  paddingRight = false,
  position = {
    character = 1,
    line = 202
  }
}
```

Quick hack that seems to fix the issue:

```lua
		local hintLines = vim.iter(result):fold({}, function(acc, hint)
			--vim.notify("󰹈 :  hint: " .. vim.inspect(hint))
			local lnum = hint.position.line
			local col = hint.position.character
			-- local label = hint.label[1].value:gsub("^:", ""):gsub(":$", "")
			local label
			if type(hint.label) == "string" then
				label = hint.label
			elseif type(hint.label) == "table" then
				label = hint.label[1].value
			end
			label = label:gsub("^:", ""):gsub(":$", "")
```

Thank you! As usual, this plugin is a nice QOL improvement.

### To Reproduce

- Open a `.rs` file with an `impl` keyword. ( [example](https://github.com/BurntSushi/ripgrep/blob/c9ebcbd8abe48c8336fb4826df7e9b6fb179de03/crates/searcher/src/line_buffer.rs#L114)
- Use default nvim-lsp-endhints options
- Enable inlay hints when rust-analyzer is attached (`vim.lsp.inlay_hint.enable(true)`)

### neovim version

```Text
NVIM v0.11.0-dev-311+g9dc09a4cd
rust-analyzer 1 (2fd803cc13 2024-06-22)
cargo 1.77.2 (e52e36006 2024-03-26)
```

**Comment by al-ce** [comment]
> Next time, if you already have a fix, why not make a PR?

Thanks for the fix. I should have mentioned it above, but I wasn't sure if just checking "string" vs. "table" would be exhaustive (e.g. maybe there's some LSPs that use `label.value` or `label[1]` etc.), but I guess that could have been addressed down the line. I'll cut right to it next time.

**Comment by chrisgrieser** [comment]
yep, stuff like that can simply be addressed on a need-to-do basis. Though I just checked, and it appears that the response can only be label.value[1] or label: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#inlayHint
