### ISSUE TITLE
Truncate the inly hint if it's more than 20 characters 

### ISSUE THREAD

**Issue by samyarkd** [chrisgrieser/nvim-lsp-endhints#10]
### Checklist

- [X] I have read the README.
- [X] The feature would be useful to more users than just me.

### Feature Requested

It's very annoying when the hint is long (it really does not help if it's too long) so i think that it would be very nice to set a custom length and truncate if it was more than that.

**Comment by chrisgrieser** [comment]
Good idea. Added as config option `labels.truncateAtChars`

**Comment by samyarkd** [comment]
that was fast thanks
