### ISSUE TITLE
Virtual text highlight not respecting cursorline background

### ISSUE THREAD

**Issue by catgoose** [chrisgrieser/nvim-lsp-endhints#2]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.
- [X] LSP inlay hints do work correctly without this plugin when using `vim.lsp.inlay_hint.enable(true)`. (If not, then the problem lies with your LSP or your LSP configuration, not this plugin.)

### Bug Description

Without plugin:

![image](https://github.com/chrisgrieser/nvim-lsp-endhints/assets/21010072/8498e36b-7a3f-4f82-9035-f3f69c869d73)

With plugin:

![image](https://github.com/chrisgrieser/nvim-lsp-endhints/assets/21010072/f182ab79-81f6-4c23-a541-32e3e0271f1f)

I use kanagawa and `LspInlayHint` highlight group links to `NonText`, but it looks like when the virtual text is created for some reason it is not displaying the same with cursorline as when the plugin is disabled

### To Reproduce

1. enable cursorline
2. set highlight group for cursorline
3. view inlay hints

### neovim version

```Text
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1713484068
```

**Comment by chrisgrieser** [comment]
Tbh, I am not sure why that happens, since the plugin does not change highlight groups at all. 🤔

**Comment by catgoose** [comment]
Could it be how the virtual text is created?

**Comment by chrisgrieser** [comment]
ah found it, there is an extmark option for that. Fixed.
