### ISSUE TITLE
Bug: Display hints only for current line doesn't work.

### ISSUE THREAD

**Issue by vunhatchuong** [chrisgrieser/nvim-lsp-endhints#3]
### Make sure you have done the following

- [X] I have updated to the latest version of the plugin.
- [X] I have read the README.
- [X] LSP inlay hints do work correctly without this plugin when using `vim.lsp.inlay_hint.enable(true)`. (If not, then the problem lies with your LSP or your LSP configuration, not this plugin.)

### Bug Description

I use the display hints only for the current line code in the [README](https://github.com/chrisgrieser/nvim-lsp-endhints?tab=readme-ov-file#how-to-display-hints-only-for-the-current-line). Which **works** only if this plugin is not enabled.

### To Reproduce

I use the default options of this plugin and the code snippet linked in `README`. The code snippet does work if I disable this plugin.

### neovim version

```Text
v0.10.0
```

**Comment by chrisgrieser** [comment]
Sorry, I haven't phrased it clearly enough in the docs. The linked snippet is not meant to complement this plugin, it's simply an alternative approach. 

To keep this plugin minimal, there are currently no plans to display hints at the end of line *and* restrict it to the current line only.
